Update for Amplify Boost Up 2023/03/10
aws-amplify-jp/amplify-meetup-cfp pull request #15
Opened 2023-01-21 05:51 UTC by kopkunka55

* Update date and time
* Update presentation time
* Archive previous README for 2021/07/30

2023-01-21 23:48 UTC, fossamagna requested changes
更新ありがとうございます。

2023-01-21 23:48 UTC, fossamagna commented on archive/20210730/README.md
> +- 7/16 (金) CFP締め切り
スケジュールが前回のままのようです。

2023-01-21 23:48 UTC, fossamagna commented on archive/20210730/README.md
> +- 登壇時間は20分です。内訳は発表時間が15分、QAが5分です
```suggestion
- 登壇時間は15分です。内訳は発表時間が10分、QAが5分です
```
ルートのREADMD.mdにあわせてこんな感じかと思います。

2023-01-21 23:54 UTC, fossamagna approved these changes

2023-01-22 01:57 UTC, ikenyal commented
過去の発表例、前回分を追加しておきましょうか！
https://aws-amplify-jp.github.io/reports/20210730-amplify-boost-up-01

2023-01-22 07:00 UTC, tacck approved these changes

2023-01-22 13:17 UTC, ikenyal approved these changes

2023-01-22 13:20 UTC, merged